DEVICE          : cuda                        # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'output/MMS-Gemini'          # output folder name used for saving the model, logs and inference results
WANDB_NAME      : 'nyu'        # name for the run
USE_WANDB       : False                       # Whether you want to use wandb
GPUs            : 1
GPU_IDs         : [0]

MODEL:
  NAME          : MMSGeminiFusion                                         # name of the model you are using
  BACKBONE      : MMSGemini-B4                                      # model variant
  PRETRAINED    : '/home/b311/data/zhangwei/MMSFormer/checkpoints/pretrained/segformer/mit_b4.pth'     # backbone model's weight 
  RESUME        : ''                                                # checkpoint file 

DATASET:
  NAME          : NYU                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/home/b311/data/zhangwei/MMSFormer/data/NYUDepthv2'                            # dataset root path
  IGNORE_LABEL  : 255
  # MODALS        : ['img'] 
  MODALS        : ['img', 'depth']

TRAIN:
  IMAGE_SIZE    : [480, 640]      # training image size in (h, w)
  BATCH_SIZE    : 2               # batch size used to train
  EPOCHS        : 500             # number of epochs to train
  EVAL_START    : 0             # evaluation interval start
  EVAL_INTERVAL : 5               # evaluation interval during training
  AMP           : true           # use AMP in training
  DDP           : false            # use DDP training
  PTH_NAME      : nyu

LOSS:
  NAME          : OhemCrossEntropy          # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.00006         # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  MODEL_PATH    : 'output/NYU_Depth_V2/cmnext_b4_nyu_rgbd.pth'
  IMAGE_SIZE    : [480, 640]      # evaluation image size in (h, w)                       
  BATCH_SIZE    : 2               # batch size used to train
  MSF: 
    ENABLE      : false                                    # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                